apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
     - image: skaffold/payment-buildkit
#    - docker:
       context: ../build/payment
  local:
    useBuildkit: true
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/app/*.yaml
